[paths]
environments_path = "./environments"
extensions_dirs = ["extensions/auth", "extensions/notifications", "extensions"]

[build]
skip_base_generation = true
extensions = ["proxy", "htpasswd", "oidc", "imagelist-conf", "step-ca-trust"]

[build.combos]
basic = ["proxy", "htpasswd"]
basic-hub = ["proxy", "htpasswd", "imagelist-conf"]
oidc-hub = ["proxy", "oidc", "imagelist-conf"]
oidc-hub-trust = ["proxy", "oidc", "imagelist-conf", "step-ca-trust"]

[build.environments]
available = ["devcontainer", "forwarding", "letsencrypt", "step-ca"]

[build.environments.devcontainer]
extensions = []
combos = ["basic"]

[build.environments.forwarding]
extensions = []
combos = ["basic"]

[build.environments.letsencrypt]
extensions = []
combos = ["basic"]

[build.environments.step-ca]
extensions = []
combos = ["basic", "basic-hub", "oidc-hub-trust"]
