services:
  distribution:
    environment:
      REGISTRY_PROXY_TTL: ${REGISTRY_PROXY_TTL:-168h}
      REGISTRY_PROXY_REMOTEURL: ${REGISTRY_PROXY_REMOTEURL}
      REGISTRY_PROXY_USERNAME: ${REGISTRY_PROXY_USERNAME:-}
      REGISTRY_PROXY_PASSWORD: ${REGISTRY_PROXY_PASSWORD:-}